
export default {
    sqrt: require("./sqrt.png"),
    cbrt: require("./cbrt.png"),
    sd: require("./sd.png"),
    fraction: require("./fraction.png"),
    "arrow-left": require("./arrow-left.png"),
    "arrow-right": require("./arrow-right.png"),
    degree: require("./degree.png"),
    delete: require("./delete.png"),
    log: require("./log.png"),
    "math_pwr": require("./math_pwr.png"),
    pwr2: require("./pwr2.png"),
    root: require("./root.png"),
    area: require("./area.png"),
    "arrow-two-way": require("./arrow-two-way.png"),
    calculator: require("./calculator.png"),
    "chevron-left": require("./chevron-left.png"),
    "chevron-selector": require("./chevron-selector.png"),
    container: require("./container.png"),
    "history-circle": require("./history-circle.png"),
    ruler: require("./ruler.png"),
    "x-xlose": require("./x-close.png"),
    "zap-fast": require("./zap-fast.png"),
    "fitness": require("./fitness.png"),
    car: require("./car.png"),
    temp: require("./temp.png"),
    clock: require("./clock.png"),
    acute: require("./acute.png"),
    quizard: require("./quizard.png"),

}
